version: '3'

services:
  web:
    image: nginx:1-alpine-slim
    depends_on:
      observer:
        condition: service_healthy
      victim:
        condition: service_healthy
    networks:
      external_network:
      internal_network:
        aliases:
          - attacker.poc.example
          - observer.poc.example
          - victim.poc.example
    ports:
      - '127.0.0.1:3000:443'
    expose:
      - '443'
    volumes:
      - ./nginx/sites-available:/etc/nginx/sites-available:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - ../assets/nginx/conf.d/common.conf:/etc/nginx/conf.d/common.conf:ro
      - ../assets/nginx/snippets:/etc/nginx/snippets:ro
      - ../assets/ssl/certs:/etc/ssl/certs:ro
      - ../assets/ssl/private:/etc/ssl/private:ro
      - ../assets/www:/var/www:ro
    healthcheck:
      test: ['CMD', 'wget', '-q', '--spider', '--proxy=off', 'http://web/']

  observer:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file: misskey.env
    networks:
      # `external_network` is required because `pnpm` insists to connect to
      # <https://registry.npmjs.org/>.
      - external_network
      - internal_network
    ports:
      - '3001:3000'
    expose:
      - '3000'
    volumes:
      - ./observer-files:/misskey/files
      - ./observer.yml:/misskey/.config/default.yml:ro
      - ../assets/ssl/certs/3409c71e.0:/etc/ssl/certs/3409c71e.0:ro
      - ../assets/ssl/certs/self-signed.pem:/etc/ssl/certs/self-signed.pem:ro

  victim:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file: misskey.env
    networks:
      - external_network
      - internal_network
    ports:
      - '3002:3000'
    expose:
      - '3000'
    volumes:
      - ./victim-files:/misskey/files
      - ./victim.yml:/misskey/.config/default.yml:ro
      - ../assets/ssl/certs/3409c71e.0:/etc/ssl/certs/3409c71e.0:ro
      - ../assets/ssl/certs/self-signed.pem:/etc/ssl/certs/self-signed.pem:ro

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - internal_network
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - internal_network
    volumes:
      - redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']

networks:
  external_network:
  internal_network:
    internal: true

volumes:
  postgres-data:
  redis-data:
